package com.example.ice_cream.enums

enum class Type {
    CONE_NORMAL, CONE_SWEET, CONE_CHOCOLATE, CONE_CHALICE,
    DRESSING_STRAWBERRY, DRESSING_VANILLA,
    OTHER_SUGAR_MAGIC, OTHER_ROLETTI, OTHER_WAFER
}